### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by JamesPD85** [JamesPD85/FlexMileage#1]
c:\Python36\Scripts\Sublime\Mileage\FlexMileage>python tkgui.py
Traceback (most recent call last):
  File "tkgui.py", line 149, in <module>
    app = FlexMileageApp()
  File "tkgui.py", line 30, in __init__
    frame.grid(row=0,column=0,sticky="nsew")
TypeError: wm_grid() got an unexpected keyword argument 'row'

Code:
```

for F in (HomePage,History,EnterMileage,LoginPage,Costs):
            frame = F(container,self)
            self.frames[F] = frame
            # unexpected keyword argument 'row'
            frame.grid(row=0,column=0,sticky="nsew")
            #       error^
```

**Comment by JamesPD85** [comment]
Turns out class Costs was inherited from tk.Tk, when it should have been tk.Frame.
